spring.application.name=stocksim
spring.datasource.url=jdbc:postgresql://db:5432/myapp
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=2s

# Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect